name: CI with OpenTelemetry

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a command with OpenTelemetry
        uses: krzko/run-with-telemetry@v1
        with:
          command: "echo 'Hello, OpenTelemetry!'"
          service_name: "github-ci-pipeline"
          endpoint: "http://18.224.135.200:4317"

      - name: Deploy Application
        run: |
          cd ~/app
          git pull origin main
          npm install
          pm2 restart my-app || pm2 start server.js --name my-app
