name: CI with OpenTelemetry

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a command with OpenTelemetry
        uses: krzko/run-with-telemetry@v0.4.3
        with:
          otel-service-name: "o11y.workflows"
          otel-exporter-otlp-endpoint: 18.218.236.254:4318
          otel-resource-attributes: "deployment.environment=dev,service.version=0.1.0"
          step-name: "Build the project with telemetry"
          run: echo hello!!!
          github-token: ${{ secrets.GITHUB_TOKEN }}
