name: CI with OpenTelemetry

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a command with OpenTelemetry
        uses: krzko/export-job-telemetry@v0.3.0
        with:
          otel-service-name: "github-ci-pipeline"
          otel-exporter-otlp-endpoint: "http://18.224.135.200:4317"
          otel-resource-attributes: "service.name=github-ci-pipeline"

      - name: Deploy Application
        run: |
          cd ~/app
          git pull origin main
          npm install
          pm2 restart my-app || pm2 start server.js --name my-app
