name: Export otel Trace for CI

on:
  workflow_run:
    workflows:
      - CI
    types: [completed]

jobs:
  otel-export-trace:
    name: OpenTelemetry Export Trace
    runs-on: ubuntu-latest
    steps:
      - name: Export Workflow Trace
        uses: corentinmusard/otel-cicd-action@v1
        with:
          otlpEndpoint: http://18.218.236.254:4318
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          runId: ${{ github.event.workflow_run.id }}
