name: CI with OpenTelemetry

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check OpenTelemetry Connectivity
        run: curl -v http://18.224.135.200:4317

      - name: Run a command with OpenTelemetry
        uses: krzko/run-with-telemetry@v0.4.3
        with:
          otel-service-name: "o11y.workflows"
          otel-exporter-otlp-endpoint: "http://18.224.135.200:4317"
          otel-resource-attributes: "deployment.environent=dev,service.version=0.1.0"
          step-name: Run a single-line command with telemetry
          run: make build

      - name: Deploy Application
        run: |
          cd ~/app
          git pull origin main
          npm install
          pm2 restart my-app || pm2 start server.js --name my-app
