name: Send Telemetry after Other Workflow

on: [push]

jobs:
  send-telemetry:
    name: Send CI Telemetry
    runs-on: ubuntu-latest
    steps:
      - name: Debug Environment Variables
        run: env | sort
      - name: Run
        id: run
        uses: paper2/github-actions-opentelemetry@main
        env:
          OTEL_SERVICE_NAME: github-actions-opentelemetry
          OTEL_EXPORTER_OTLP_ENDPOINT: 3.17.152.199:4318
        with:
          # Required for collecting workflow data
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 


      - name: Deploy Application
        run: |
          cd ~/app
          git pull origin main
          npm install
          pm2 restart my-app || pm2 start server.js --name my-app
