name: Send Telemetry after Other Workflow

on:
  workflow_run:
    workflows:
      - CI
    # This action uses completed workflow for making traces and metrics.
    types:
      - completed

jobs:
  send-telemetry:
    name: Send CI Telemetry
    runs-on: ubuntu-latest
    steps:
      - name: github token
        uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Run
        id: run
        uses: paper2/github-actions-opentelemetry@main
        env:
          OTEL_SERVICE_NAME: github-actions-opentelemetry
          OTEL_EXPORTER_OTLP_ENDPOINT: 3.129.89.53:4318
        with:
          # Required for collecting workflow data #
          GITHUB_TOKEN: ${{ github.token }} 
